// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6oWWJ5VKl2r5j9Tur-CRwhBOmr9kProY',
    appId: '1:638904186507:web:42e639b82b0b686e69c68e',
    messagingSenderId: '638904186507',
    projectId: 'stats-1da68',
    authDomain: 'stats-1da68.firebaseapp.com',
    storageBucket: 'stats-1da68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgIqzlTnHnu_7aplvchmMIWcoamEbbhpQ',
    appId: '1:638904186507:android:093ef9a65b3ec8df69c68e',
    messagingSenderId: '638904186507',
    projectId: 'stats-1da68',
    storageBucket: 'stats-1da68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRVNE52c7uVqoDQxG1RmA3WXhofZh64w',
    appId: '1:638904186507:ios:22bae05f6992b09c69c68e',
    messagingSenderId: '638904186507',
    projectId: 'stats-1da68',
    storageBucket: 'stats-1da68.appspot.com',
    androidClientId: '638904186507-43sbcfpp9kqnjo708agmj5mca13e6b2c.apps.googleusercontent.com',
    iosClientId: '638904186507-cndgo4fcf71bqj45k38k49r7qgujuubf.apps.googleusercontent.com',
    iosBundleId: 'com.example.statsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcRVNE52c7uVqoDQxG1RmA3WXhofZh64w',
    appId: '1:638904186507:ios:22bae05f6992b09c69c68e',
    messagingSenderId: '638904186507',
    projectId: 'stats-1da68',
    storageBucket: 'stats-1da68.appspot.com',
    androidClientId: '638904186507-43sbcfpp9kqnjo708agmj5mca13e6b2c.apps.googleusercontent.com',
    iosClientId: '638904186507-cndgo4fcf71bqj45k38k49r7qgujuubf.apps.googleusercontent.com',
    iosBundleId: 'com.example.statsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6oWWJ5VKl2r5j9Tur-CRwhBOmr9kProY',
    appId: '1:638904186507:web:74e784173cabadf669c68e',
    messagingSenderId: '638904186507',
    projectId: 'stats-1da68',
    authDomain: 'stats-1da68.firebaseapp.com',
    storageBucket: 'stats-1da68.appspot.com',
  );

}